"""Initial_migration

Revision ID: 49637b79924b
Revises: 
Create Date: 2025-12-08 00:51:32.072529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49637b79924b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    op.drop_constraint(op.f('category_user_id_fkey'), 'category', type_='foreignkey')
    op.drop_column('category', 'user_id')
    
    # 1. Add column as nullable first
    op.add_column('expense', sa.Column('category_id', sa.Integer(), nullable=True))
    
    # 2. Data Migration: Ensure categories exist and map IDs
    # Insert missing categories (Postgres specific syntax for 'NOW()', can use CURRENT_TIMESTAMP)
    op.execute(
        "INSERT INTO category (name, color, created_at) "
        "SELECT DISTINCT category, '#64748b', CURRENT_TIMESTAMP "
        "FROM expense "
        "WHERE category NOT IN (SELECT name FROM category)"
    )
    
    # Update category_id mapping
    op.execute(
        "UPDATE expense SET category_id = (SELECT id FROM category WHERE name = expense.category)"
    )
    
    # 3. Alter to not null
    op.alter_column('expense', 'category_id', nullable=False)
    
    op.create_foreign_key(None, 'expense', 'category', ['category_id'], ['id'])
    op.drop_column('expense', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'expense', type_='foreignkey')
    op.drop_column('expense', 'category_id')
    op.add_column('category', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('category_user_id_fkey'), 'category', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=False)
    # ### end Alembic commands ###
