"""Initial_migration

Revision ID: 49637b79924b
Revises: 
Create Date: 2025-12-08 00:51:32.072529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49637b79924b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


import sqlmodel

def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    
    if not inspector.has_table('user'):
        # Fresh Database: Create all tables in their final state
        op.create_table('category',
            sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
        
        op.create_table('user',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
        
        op.create_table('expense',
            sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('amount', sa.Float(), nullable=False),
            sa.Column('category_id', sa.Integer(), nullable=False),
            sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('date', sa.DateTime(), nullable=False),
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
            sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    else:
        # Existing Database (Legacy): Refactor tables
        print("Detected existing tables, running refactoring logic...")
        op.drop_index(op.f('ix_category_name'), table_name='category')
        op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
        op.drop_constraint(op.f('category_user_id_fkey'), 'category', type_='foreignkey')
        op.drop_column('category', 'user_id')
        
        # 1. Add column as nullable first
        op.add_column('expense', sa.Column('category_id', sa.Integer(), nullable=True))
        
        # 2. Data Migration: Ensure categories exist and map IDs
        # Insert missing categories (Postgres specific syntax for 'NOW()', can use CURRENT_TIMESTAMP)
        op.execute(
            "INSERT INTO category (name, color, created_at) "
            "SELECT DISTINCT category, '#64748b', CURRENT_TIMESTAMP "
            "FROM expense "
            "WHERE category NOT IN (SELECT name FROM category)"
        )
        
        # Update category_id mapping
        op.execute(
            "UPDATE expense SET category_id = (SELECT id FROM category WHERE name = expense.category)"
        )
        
        # 3. Alter to not null
        op.alter_column('expense', 'category_id', nullable=False)
        
        op.create_foreign_key(None, 'expense', 'category', ['category_id'], ['id'])
        op.drop_column('expense', 'category')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'expense', type_='foreignkey')
    op.drop_column('expense', 'category_id')
    op.add_column('category', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('category_user_id_fkey'), 'category', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=False)
    # ### end Alembic commands ###
